GO_VERSION := $(shell cat .go-version)
GO ?= go
GOBIN ?= $(CURDIR)/bin
GO_SOURCE_DIRS := $(wildcard cmd internal test hack/tools)
AST_GREP ?= .github/tools/node_modules/.bin/ast-grep
SEMGREP ?= semgrep
GOFUMPT ?= $(if $(wildcard $(GOBIN)/gofumpt),$(GOBIN)/gofumpt,gofumpt)
STATICCHECK ?= $(if $(wildcard $(GOBIN)/staticcheck),$(GOBIN)/staticcheck,staticcheck)
GOVULNCHECK ?= $(if $(wildcard $(GOBIN)/govulncheck),$(GOBIN)/govulncheck,govulncheck)
GOLANGCI_LINT ?= $(if $(wildcard $(GOBIN)/golangci-lint),$(GOBIN)/golangci-lint,golangci-lint)
GO_LICENSES ?= $(if $(wildcard $(GOBIN)/go-licenses),$(GOBIN)/go-licenses,go-licenses)
BUF ?= $(if $(wildcard $(GOBIN)/buf),$(GOBIN)/buf,buf)
PROTOC_GEN_GO ?= $(if $(wildcard $(GOBIN)/protoc-gen-go),$(GOBIN)/protoc-gen-go,protoc-gen-go)
PROTOC_GEN_GO_GRPC ?= $(if $(wildcard $(GOBIN)/protoc-gen-go-grpc),$(GOBIN)/protoc-gen-go-grpc,protoc-gen-go-grpc)
TRIVY ?= trivy
SEMGREP_CONFIG_FLAGS ?= --config .semgrep/rules
SEMGREP_TARGETS ?= cmd internal .github
SEMGREP_ARTIFACT_DIR ?= dist/semgrep
SEMGREP_OUTPUT_JSON ?= $(SEMGREP_ARTIFACT_DIR)/semgrep.json

PLUGIN_BINARY_NAME ?= bao-kms-unseal
BROKER_BINARY_NAME ?= bao-unseald
CTL_BINARY_NAME ?= bao-unsealctl
DIST_DIR ?= dist/release
CHECKSUM_FILE ?= $(DIST_DIR)/checksums.txt
CHECKSUM ?= shasum -a 256
RELEASE_TARGETS ?= linux/amd64 linux/arm64
VERSION ?= 0.0.0-dev
COMMIT ?= $(shell git rev-parse --short HEAD 2>/dev/null || printf '%s' unknown)
BUILD_DATE ?= $(shell if [ -n "$${SOURCE_DATE_EPOCH:-}" ]; then date -u -r "$${SOURCE_DATE_EPOCH}" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "@$${SOURCE_DATE_EPOCH}" +%Y-%m-%dT%H:%M:%SZ; else date -u +%Y-%m-%dT%H:%M:%SZ; fi)
DIRTY ?= $(shell if [ -n "$$(git status --porcelain 2>/dev/null)" ]; then printf '%s' true; else printf '%s' false; fi)
VERSION_PKG := github.com/adfinis/openbao-attested-unseal/internal/version
GO_BUILD_FLAGS ?= -trimpath -buildvcs=false
LDFLAGS := -s -w -X $(VERSION_PKG).version=$(VERSION) -X $(VERSION_PKG).commit=$(COMMIT) -X $(VERSION_PKG).buildDate=$(BUILD_DATE) -X $(VERSION_PKG).dirty=$(DIRTY)

GOFUMPT_VERSION ?= v0.8.0
STATICCHECK_VERSION ?= v0.6.1
GOVULNCHECK_VERSION ?= v1.1.4
GOLANGCI_LINT_VERSION ?= v2.5.0
GO_LICENSES_VERSION ?= v2.0.1
BUF_VERSION ?= v1.71.0
PROTOC_GEN_GO_VERSION ?= v1.36.11
PROTOC_GEN_GO_GRPC_VERSION ?= v1.6.2
GO_LICENSES_ALLOWED ?= Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT MPL-2.0 Unicode-DFS-2016
GO_LICENSES_IGNORE ?= github.com/adfinis/openbao-attested-unseal
GO_LICENSES_PACKAGE_TARGETS ?= ./cmd/bao-kms-unseal ./cmd/bao-unseald ./cmd/bao-unsealctl
LICENSE_REPORT_DIR ?= dist/licenses
go_licenses_empty :=
go_licenses_space := $(go_licenses_empty) $(go_licenses_empty)
go_licenses_comma := ,
GO_LICENSES_ALLOWED_CSV := $(subst $(go_licenses_space),$(go_licenses_comma),$(strip $(GO_LICENSES_ALLOWED)))
