// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openbao/attestedunseal/v1/attestedunseal.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_WRAP        Operation = 1
	Operation_OPERATION_UNWRAP      Operation = 2
	Operation_OPERATION_ENROLL      Operation = 3
	Operation_OPERATION_ROTATE      Operation = 4
	Operation_OPERATION_RECOVER     Operation = 5
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_WRAP",
		2: "OPERATION_UNWRAP",
		3: "OPERATION_ENROLL",
		4: "OPERATION_ROTATE",
		5: "OPERATION_RECOVER",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_WRAP":        1,
		"OPERATION_UNWRAP":      2,
		"OPERATION_ENROLL":      3,
		"OPERATION_ROTATE":      4,
		"OPERATION_RECOVER":     5,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{0}
}

type AttestationProvider int32

const (
	AttestationProvider_ATTESTATION_PROVIDER_UNSPECIFIED         AttestationProvider = 0
	AttestationProvider_ATTESTATION_PROVIDER_TPM2_QUOTE          AttestationProvider = 1
	AttestationProvider_ATTESTATION_PROVIDER_KUBERNETES_WORKLOAD AttestationProvider = 2
)

// Enum value maps for AttestationProvider.
var (
	AttestationProvider_name = map[int32]string{
		0: "ATTESTATION_PROVIDER_UNSPECIFIED",
		1: "ATTESTATION_PROVIDER_TPM2_QUOTE",
		2: "ATTESTATION_PROVIDER_KUBERNETES_WORKLOAD",
	}
	AttestationProvider_value = map[string]int32{
		"ATTESTATION_PROVIDER_UNSPECIFIED":         0,
		"ATTESTATION_PROVIDER_TPM2_QUOTE":          1,
		"ATTESTATION_PROVIDER_KUBERNETES_WORKLOAD": 2,
	}
)

func (x AttestationProvider) Enum() *AttestationProvider {
	p := new(AttestationProvider)
	*p = x
	return p
}

func (x AttestationProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestationProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[1].Descriptor()
}

func (AttestationProvider) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[1]
}

func (x AttestationProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestationProvider.Descriptor instead.
func (AttestationProvider) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{1}
}

type PolicyDecisionState int32

const (
	PolicyDecisionState_POLICY_DECISION_STATE_UNSPECIFIED PolicyDecisionState = 0
	PolicyDecisionState_POLICY_DECISION_STATE_ALLOW       PolicyDecisionState = 1
	PolicyDecisionState_POLICY_DECISION_STATE_DENY        PolicyDecisionState = 2
)

// Enum value maps for PolicyDecisionState.
var (
	PolicyDecisionState_name = map[int32]string{
		0: "POLICY_DECISION_STATE_UNSPECIFIED",
		1: "POLICY_DECISION_STATE_ALLOW",
		2: "POLICY_DECISION_STATE_DENY",
	}
	PolicyDecisionState_value = map[string]int32{
		"POLICY_DECISION_STATE_UNSPECIFIED": 0,
		"POLICY_DECISION_STATE_ALLOW":       1,
		"POLICY_DECISION_STATE_DENY":        2,
	}
)

func (x PolicyDecisionState) Enum() *PolicyDecisionState {
	p := new(PolicyDecisionState)
	*p = x
	return p
}

func (x PolicyDecisionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyDecisionState) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[2].Descriptor()
}

func (PolicyDecisionState) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[2]
}

func (x PolicyDecisionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyDecisionState.Descriptor instead.
func (PolicyDecisionState) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{2}
}

type KeyStatus int32

const (
	KeyStatus_KEY_STATUS_UNSPECIFIED  KeyStatus = 0
	KeyStatus_KEY_STATUS_PENDING      KeyStatus = 1
	KeyStatus_KEY_STATUS_ACTIVE       KeyStatus = 2
	KeyStatus_KEY_STATUS_DECRYPT_ONLY KeyStatus = 3
	KeyStatus_KEY_STATUS_RETIRED      KeyStatus = 4
)

// Enum value maps for KeyStatus.
var (
	KeyStatus_name = map[int32]string{
		0: "KEY_STATUS_UNSPECIFIED",
		1: "KEY_STATUS_PENDING",
		2: "KEY_STATUS_ACTIVE",
		3: "KEY_STATUS_DECRYPT_ONLY",
		4: "KEY_STATUS_RETIRED",
	}
	KeyStatus_value = map[string]int32{
		"KEY_STATUS_UNSPECIFIED":  0,
		"KEY_STATUS_PENDING":      1,
		"KEY_STATUS_ACTIVE":       2,
		"KEY_STATUS_DECRYPT_ONLY": 3,
		"KEY_STATUS_RETIRED":      4,
	}
)

func (x KeyStatus) Enum() *KeyStatus {
	p := new(KeyStatus)
	*p = x
	return p
}

func (x KeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[3].Descriptor()
}

func (KeyStatus) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[3]
}

func (x KeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyStatus.Descriptor instead.
func (KeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{3}
}

type NodeEvidenceStatus int32

const (
	NodeEvidenceStatus_NODE_EVIDENCE_STATUS_UNSPECIFIED NodeEvidenceStatus = 0
	NodeEvidenceStatus_NODE_EVIDENCE_STATUS_FRESH       NodeEvidenceStatus = 1
	NodeEvidenceStatus_NODE_EVIDENCE_STATUS_STALE       NodeEvidenceStatus = 2
	NodeEvidenceStatus_NODE_EVIDENCE_STATUS_MISSING     NodeEvidenceStatus = 3
	NodeEvidenceStatus_NODE_EVIDENCE_STATUS_INVALID     NodeEvidenceStatus = 4
)

// Enum value maps for NodeEvidenceStatus.
var (
	NodeEvidenceStatus_name = map[int32]string{
		0: "NODE_EVIDENCE_STATUS_UNSPECIFIED",
		1: "NODE_EVIDENCE_STATUS_FRESH",
		2: "NODE_EVIDENCE_STATUS_STALE",
		3: "NODE_EVIDENCE_STATUS_MISSING",
		4: "NODE_EVIDENCE_STATUS_INVALID",
	}
	NodeEvidenceStatus_value = map[string]int32{
		"NODE_EVIDENCE_STATUS_UNSPECIFIED": 0,
		"NODE_EVIDENCE_STATUS_FRESH":       1,
		"NODE_EVIDENCE_STATUS_STALE":       2,
		"NODE_EVIDENCE_STATUS_MISSING":     3,
		"NODE_EVIDENCE_STATUS_INVALID":     4,
	}
)

func (x NodeEvidenceStatus) Enum() *NodeEvidenceStatus {
	p := new(NodeEvidenceStatus)
	*p = x
	return p
}

func (x NodeEvidenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEvidenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[4].Descriptor()
}

func (NodeEvidenceStatus) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[4]
}

func (x NodeEvidenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEvidenceStatus.Descriptor instead.
func (NodeEvidenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{4}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED        ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST    ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED    ErrorCode = 2
	ErrorCode_ERROR_CODE_PERMISSION_DENIED  ErrorCode = 3
	ErrorCode_ERROR_CODE_KEY_NOT_FOUND      ErrorCode = 4
	ErrorCode_ERROR_CODE_KEY_NOT_USABLE     ErrorCode = 5
	ErrorCode_ERROR_CODE_ATTESTATION_FAILED ErrorCode = 6
	ErrorCode_ERROR_CODE_BROKER_UNAVAILABLE ErrorCode = 7
	ErrorCode_ERROR_CODE_INTERNAL           ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_REQUEST",
		2: "ERROR_CODE_UNAUTHENTICATED",
		3: "ERROR_CODE_PERMISSION_DENIED",
		4: "ERROR_CODE_KEY_NOT_FOUND",
		5: "ERROR_CODE_KEY_NOT_USABLE",
		6: "ERROR_CODE_ATTESTATION_FAILED",
		7: "ERROR_CODE_BROKER_UNAVAILABLE",
		8: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":        0,
		"ERROR_CODE_INVALID_REQUEST":    1,
		"ERROR_CODE_UNAUTHENTICATED":    2,
		"ERROR_CODE_PERMISSION_DENIED":  3,
		"ERROR_CODE_KEY_NOT_FOUND":      4,
		"ERROR_CODE_KEY_NOT_USABLE":     5,
		"ERROR_CODE_ATTESTATION_FAILED": 6,
		"ERROR_CODE_BROKER_UNAVAILABLE": 7,
		"ERROR_CODE_INTERNAL":           8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[5].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes[5]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{5}
}

type AuditContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditContext) Reset() {
	*x = AuditContext{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditContext) ProtoMessage() {}

func (x *AuditContext) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditContext.ProtoReflect.Descriptor instead.
func (*AuditContext) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{0}
}

func (x *AuditContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type KeyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRef) Reset() {
	*x = KeyRef{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRef) ProtoMessage() {}

func (x *KeyRef) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRef.ProtoReflect.Descriptor instead.
func (*KeyRef) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{1}
}

func (x *KeyRef) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *KeyRef) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyRef) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type KeyVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *KeyRef                `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status        KeyStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=openbao.attestedunseal.v1.KeyStatus" json:"status,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyVersion) Reset() {
	*x = KeyVersion{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVersion) ProtoMessage() {}

func (x *KeyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVersion.ProtoReflect.Descriptor instead.
func (*KeyVersion) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{2}
}

func (x *KeyVersion) GetRef() *KeyRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *KeyVersion) GetStatus() KeyStatus {
	if x != nil {
		return x.Status
	}
	return KeyStatus_KEY_STATUS_UNSPECIFIED
}

func (x *KeyVersion) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *KeyVersion) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type BrokerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=openbao.attestedunseal.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerError) Reset() {
	*x = BrokerError{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerError) ProtoMessage() {}

func (x *BrokerError) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerError.ProtoReflect.Descriptor instead.
func (*BrokerError) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{3}
}

func (x *BrokerError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *BrokerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Operation     Operation              `protobuf:"varint,3,opt,name=operation,proto3,enum=openbao.attestedunseal.v1.Operation" json:"operation,omitempty"`
	Audit         *AuditContext          `protobuf:"bytes,4,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{4}
}

func (x *ChallengeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ChallengeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChallengeRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *ChallengeRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type ChallengeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId        string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Nonce              []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresUnixSeconds int64                  `protobuf:"varint,3,opt,name=expires_unix_seconds,json=expiresUnixSeconds,proto3" json:"expires_unix_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{5}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ChallengeResponse) GetExpiresUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresUnixSeconds
	}
	return 0
}

type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{6}
}

func (x *Claim) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Claim) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Claim) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClaimsEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        []*Claim               `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimsEnvelope) Reset() {
	*x = ClaimsEnvelope{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimsEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimsEnvelope) ProtoMessage() {}

func (x *ClaimsEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimsEnvelope.ProtoReflect.Descriptor instead.
func (*ClaimsEnvelope) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimsEnvelope) GetClaims() []*Claim {
	if x != nil {
		return x.Claims
	}
	return nil
}

type EvidenceEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Provider         AttestationProvider    `protobuf:"varint,1,opt,name=provider,proto3,enum=openbao.attestedunseal.v1.AttestationProvider" json:"provider,omitempty"`
	Format           string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Payload          []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ChallengeId      string                 `protobuf:"bytes,4,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	NormalizedClaims []*Claim               `protobuf:"bytes,5,rep,name=normalized_claims,json=normalizedClaims,proto3" json:"normalized_claims,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvidenceEnvelope) Reset() {
	*x = EvidenceEnvelope{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceEnvelope) ProtoMessage() {}

func (x *EvidenceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceEnvelope.ProtoReflect.Descriptor instead.
func (*EvidenceEnvelope) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{8}
}

func (x *EvidenceEnvelope) GetProvider() AttestationProvider {
	if x != nil {
		return x.Provider
	}
	return AttestationProvider_ATTESTATION_PROVIDER_UNSPECIFIED
}

func (x *EvidenceEnvelope) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *EvidenceEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EvidenceEnvelope) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *EvidenceEnvelope) GetNormalizedClaims() []*Claim {
	if x != nil {
		return x.NormalizedClaims
	}
	return nil
}

type NodeEvidenceRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClusterId            string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName             string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeUid              string                 `protobuf:"bytes,3,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	Provider             AttestationProvider    `protobuf:"varint,4,opt,name=provider,proto3,enum=openbao.attestedunseal.v1.AttestationProvider" json:"provider,omitempty"`
	EvidenceHash         string                 `protobuf:"bytes,5,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	CollectedUnixSeconds int64                  `protobuf:"varint,6,opt,name=collected_unix_seconds,json=collectedUnixSeconds,proto3" json:"collected_unix_seconds,omitempty"`
	ExpiresUnixSeconds   int64                  `protobuf:"varint,7,opt,name=expires_unix_seconds,json=expiresUnixSeconds,proto3" json:"expires_unix_seconds,omitempty"`
	PolicyId             string                 `protobuf:"bytes,8,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Claims               []*Claim               `protobuf:"bytes,9,rep,name=claims,proto3" json:"claims,omitempty"`
	Status               NodeEvidenceStatus     `protobuf:"varint,10,opt,name=status,proto3,enum=openbao.attestedunseal.v1.NodeEvidenceStatus" json:"status,omitempty"`
	Errors               []*BrokerError         `protobuf:"bytes,11,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeEvidenceRecord) Reset() {
	*x = NodeEvidenceRecord{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvidenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvidenceRecord) ProtoMessage() {}

func (x *NodeEvidenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvidenceRecord.ProtoReflect.Descriptor instead.
func (*NodeEvidenceRecord) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{9}
}

func (x *NodeEvidenceRecord) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeEvidenceRecord) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeEvidenceRecord) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *NodeEvidenceRecord) GetProvider() AttestationProvider {
	if x != nil {
		return x.Provider
	}
	return AttestationProvider_ATTESTATION_PROVIDER_UNSPECIFIED
}

func (x *NodeEvidenceRecord) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *NodeEvidenceRecord) GetCollectedUnixSeconds() int64 {
	if x != nil {
		return x.CollectedUnixSeconds
	}
	return 0
}

func (x *NodeEvidenceRecord) GetExpiresUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresUnixSeconds
	}
	return 0
}

func (x *NodeEvidenceRecord) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *NodeEvidenceRecord) GetClaims() []*Claim {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *NodeEvidenceRecord) GetStatus() NodeEvidenceStatus {
	if x != nil {
		return x.Status
	}
	return NodeEvidenceStatus_NODE_EVIDENCE_STATUS_UNSPECIFIED
}

func (x *NodeEvidenceRecord) GetErrors() []*BrokerError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type NodeEvidenceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Audit         *AuditContext          `protobuf:"bytes,3,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvidenceListRequest) Reset() {
	*x = NodeEvidenceListRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvidenceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvidenceListRequest) ProtoMessage() {}

func (x *NodeEvidenceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvidenceListRequest.ProtoReflect.Descriptor instead.
func (*NodeEvidenceListRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{10}
}

func (x *NodeEvidenceListRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeEvidenceListRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeEvidenceListRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type NodeEvidenceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      []*NodeEvidenceRecord  `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Decision      *PolicyDecision        `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvidenceListResponse) Reset() {
	*x = NodeEvidenceListResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvidenceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvidenceListResponse) ProtoMessage() {}

func (x *NodeEvidenceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvidenceListResponse.ProtoReflect.Descriptor instead.
func (*NodeEvidenceListResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{11}
}

func (x *NodeEvidenceListResponse) GetEvidence() []*NodeEvidenceRecord {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *NodeEvidenceListResponse) GetDecision() *PolicyDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type PolicyDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PolicyDecisionState    `protobuf:"varint,1,opt,name=state,proto3,enum=openbao.attestedunseal.v1.PolicyDecisionState" json:"state,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Errors        []*BrokerError         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDecision) Reset() {
	*x = PolicyDecision{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDecision) ProtoMessage() {}

func (x *PolicyDecision) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDecision.ProtoReflect.Descriptor instead.
func (*PolicyDecision) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{12}
}

func (x *PolicyDecision) GetState() PolicyDecisionState {
	if x != nil {
		return x.State
	}
	return PolicyDecisionState_POLICY_DECISION_STATE_UNSPECIFIED
}

func (x *PolicyDecision) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyDecision) GetErrors() []*BrokerError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type WrappedBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Iv            []byte                 `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	Key           *KeyRef                `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Mechanism     uint64                 `protobuf:"varint,4,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrappedBlob) Reset() {
	*x = WrappedBlob{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedBlob) ProtoMessage() {}

func (x *WrappedBlob) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedBlob.ProtoReflect.Descriptor instead.
func (*WrappedBlob) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{13}
}

func (x *WrappedBlob) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *WrappedBlob) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *WrappedBlob) GetKey() *KeyRef {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WrappedBlob) GetMechanism() uint64 {
	if x != nil {
		return x.Mechanism
	}
	return 0
}

type WrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedKey  *KeyRef                `protobuf:"bytes,1,opt,name=requested_key,json=requestedKey,proto3" json:"requested_key,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Aad           []byte                 `protobuf:"bytes,3,opt,name=aad,proto3" json:"aad,omitempty"`
	Evidence      *EvidenceEnvelope      `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Audit         *AuditContext          `protobuf:"bytes,5,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapRequest) Reset() {
	*x = WrapRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapRequest) ProtoMessage() {}

func (x *WrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapRequest.ProtoReflect.Descriptor instead.
func (*WrapRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{14}
}

func (x *WrapRequest) GetRequestedKey() *KeyRef {
	if x != nil {
		return x.RequestedKey
	}
	return nil
}

func (x *WrapRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *WrapRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *WrapRequest) GetEvidence() *EvidenceEnvelope {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *WrapRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type WrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          *WrappedBlob           `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Decision      *PolicyDecision        `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapResponse) Reset() {
	*x = WrapResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapResponse) ProtoMessage() {}

func (x *WrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapResponse.ProtoReflect.Descriptor instead.
func (*WrapResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{15}
}

func (x *WrapResponse) GetBlob() *WrappedBlob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *WrapResponse) GetDecision() *PolicyDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type UnwrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          *WrappedBlob           `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Aad           []byte                 `protobuf:"bytes,2,opt,name=aad,proto3" json:"aad,omitempty"`
	Evidence      *EvidenceEnvelope      `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Audit         *AuditContext          `protobuf:"bytes,4,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapRequest) Reset() {
	*x = UnwrapRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapRequest) ProtoMessage() {}

func (x *UnwrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapRequest.ProtoReflect.Descriptor instead.
func (*UnwrapRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{16}
}

func (x *UnwrapRequest) GetBlob() *WrappedBlob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *UnwrapRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *UnwrapRequest) GetEvidence() *EvidenceEnvelope {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *UnwrapRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type UnwrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Decision      *PolicyDecision        `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapResponse) Reset() {
	*x = UnwrapResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapResponse) ProtoMessage() {}

func (x *UnwrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapResponse.ProtoReflect.Descriptor instead.
func (*UnwrapResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{17}
}

func (x *UnwrapResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *UnwrapResponse) GetDecision() *PolicyDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Audit         *AuditContext          `protobuf:"bytes,2,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{18}
}

func (x *StatusRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *StatusRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyVersion          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ActiveKeyId   string                 `protobuf:"bytes,2,opt,name=active_key_id,json=activeKeyId,proto3" json:"active_key_id,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	Errors        []*BrokerError         `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{19}
}

func (x *StatusResponse) GetKeys() []*KeyVersion {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *StatusResponse) GetActiveKeyId() string {
	if x != nil {
		return x.ActiveKeyId
	}
	return ""
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusResponse) GetErrors() []*BrokerError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type EnrollmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audit         *AuditContext          `protobuf:"bytes,1,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentStatusRequest) Reset() {
	*x = EnrollmentStatusRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentStatusRequest) ProtoMessage() {}

func (x *EnrollmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentStatusRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{20}
}

func (x *EnrollmentStatusRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type EnrollmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implemented   bool                   `protobuf:"varint,1,opt,name=implemented,proto3" json:"implemented,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentStatusResponse) Reset() {
	*x = EnrollmentStatusResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentStatusResponse) ProtoMessage() {}

func (x *EnrollmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentStatusResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{21}
}

func (x *EnrollmentStatusResponse) GetImplemented() bool {
	if x != nil {
		return x.Implemented
	}
	return false
}

func (x *EnrollmentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RecoveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audit         *AuditContext          `protobuf:"bytes,1,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryStatusRequest) Reset() {
	*x = RecoveryStatusRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStatusRequest) ProtoMessage() {}

func (x *RecoveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStatusRequest.ProtoReflect.Descriptor instead.
func (*RecoveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{22}
}

func (x *RecoveryStatusRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type RecoveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implemented   bool                   `protobuf:"varint,1,opt,name=implemented,proto3" json:"implemented,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryStatusResponse) Reset() {
	*x = RecoveryStatusResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStatusResponse) ProtoMessage() {}

func (x *RecoveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStatusResponse.ProtoReflect.Descriptor instead.
func (*RecoveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{23}
}

func (x *RecoveryStatusResponse) GetImplemented() bool {
	if x != nil {
		return x.Implemented
	}
	return false
}

func (x *RecoveryStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audit         *AuditContext          `protobuf:"bytes,1,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatusRequest) Reset() {
	*x = AdminStatusRequest{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatusRequest) ProtoMessage() {}

func (x *AdminStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatusRequest.ProtoReflect.Descriptor instead.
func (*AdminStatusRequest) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{24}
}

func (x *AdminStatusRequest) GetAudit() *AuditContext {
	if x != nil {
		return x.Audit
	}
	return nil
}

type AdminStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implemented   bool                   `protobuf:"varint,1,opt,name=implemented,proto3" json:"implemented,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatusResponse) Reset() {
	*x = AdminStatusResponse{}
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatusResponse) ProtoMessage() {}

func (x *AdminStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminStatusResponse) Descriptor() ([]byte, []int) {
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP(), []int{25}
}

func (x *AdminStatusResponse) GetImplemented() bool {
	if x != nil {
		return x.Implemented
	}
	return false
}

func (x *AdminStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_openbao_attestedunseal_v1_attestedunseal_proto protoreflect.FileDescriptor

const file_openbao_attestedunseal_v1_attestedunseal_proto_rawDesc = "" +
	"\n" +
	".openbao/attestedunseal/v1/attestedunseal.proto\x12\x19openbao.attestedunseal.v1\"T\n" +
	"\fAuditContext\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"X\n" +
	"\x06KeyRef\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"\xba\x01\n" +
	"\n" +
	"KeyVersion\x123\n" +
	"\x03ref\x18\x01 \x01(\v2!.openbao.attestedunseal.v1.KeyRefR\x03ref\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.openbao.attestedunseal.v1.KeyStatusR\x06status\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\"a\n" +
	"\vBrokerError\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.openbao.attestedunseal.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x01\n" +
	"\x10ChallengeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12B\n" +
	"\toperation\x18\x03 \x01(\x0e2$.openbao.attestedunseal.v1.OperationR\toperation\x12=\n" +
	"\x05audit\x18\x04 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"~\n" +
	"\x11ChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x120\n" +
	"\x14expires_unix_seconds\x18\x03 \x01(\x03R\x12expiresUnixSeconds\"O\n" +
	"\x05Claim\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"J\n" +
	"\x0eClaimsEnvelope\x128\n" +
	"\x06claims\x18\x01 \x03(\v2 .openbao.attestedunseal.v1.ClaimR\x06claims\"\x82\x02\n" +
	"\x10EvidenceEnvelope\x12J\n" +
	"\bprovider\x18\x01 \x01(\x0e2..openbao.attestedunseal.v1.AttestationProviderR\bprovider\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fchallenge_id\x18\x04 \x01(\tR\vchallengeId\x12M\n" +
	"\x11normalized_claims\x18\x05 \x03(\v2 .openbao.attestedunseal.v1.ClaimR\x10normalizedClaims\"\xa2\x04\n" +
	"\x12NodeEvidenceRecord\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bnode_uid\x18\x03 \x01(\tR\anodeUid\x12J\n" +
	"\bprovider\x18\x04 \x01(\x0e2..openbao.attestedunseal.v1.AttestationProviderR\bprovider\x12#\n" +
	"\revidence_hash\x18\x05 \x01(\tR\fevidenceHash\x124\n" +
	"\x16collected_unix_seconds\x18\x06 \x01(\x03R\x14collectedUnixSeconds\x120\n" +
	"\x14expires_unix_seconds\x18\a \x01(\x03R\x12expiresUnixSeconds\x12\x1b\n" +
	"\tpolicy_id\x18\b \x01(\tR\bpolicyId\x128\n" +
	"\x06claims\x18\t \x03(\v2 .openbao.attestedunseal.v1.ClaimR\x06claims\x12E\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2-.openbao.attestedunseal.v1.NodeEvidenceStatusR\x06status\x12>\n" +
	"\x06errors\x18\v \x03(\v2&.openbao.attestedunseal.v1.BrokerErrorR\x06errors\"\x94\x01\n" +
	"\x17NodeEvidenceListRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12=\n" +
	"\x05audit\x18\x03 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"\xac\x01\n" +
	"\x18NodeEvidenceListResponse\x12I\n" +
	"\bevidence\x18\x01 \x03(\v2-.openbao.attestedunseal.v1.NodeEvidenceRecordR\bevidence\x12E\n" +
	"\bdecision\x18\x02 \x01(\v2).openbao.attestedunseal.v1.PolicyDecisionR\bdecision\"\xb3\x01\n" +
	"\x0ePolicyDecision\x12D\n" +
	"\x05state\x18\x01 \x01(\x0e2..openbao.attestedunseal.v1.PolicyDecisionStateR\x05state\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12>\n" +
	"\x06errors\x18\x03 \x03(\v2&.openbao.attestedunseal.v1.BrokerErrorR\x06errors\"\x90\x01\n" +
	"\vWrappedBlob\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x0e\n" +
	"\x02iv\x18\x02 \x01(\fR\x02iv\x123\n" +
	"\x03key\x18\x03 \x01(\v2!.openbao.attestedunseal.v1.KeyRefR\x03key\x12\x1c\n" +
	"\tmechanism\x18\x04 \x01(\x04R\tmechanism\"\x8d\x02\n" +
	"\vWrapRequest\x12F\n" +
	"\rrequested_key\x18\x01 \x01(\v2!.openbao.attestedunseal.v1.KeyRefR\frequestedKey\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03aad\x18\x03 \x01(\fR\x03aad\x12G\n" +
	"\bevidence\x18\x04 \x01(\v2+.openbao.attestedunseal.v1.EvidenceEnvelopeR\bevidence\x12=\n" +
	"\x05audit\x18\x05 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"\x91\x01\n" +
	"\fWrapResponse\x12:\n" +
	"\x04blob\x18\x01 \x01(\v2&.openbao.attestedunseal.v1.WrappedBlobR\x04blob\x12E\n" +
	"\bdecision\x18\x02 \x01(\v2).openbao.attestedunseal.v1.PolicyDecisionR\bdecision\"\xe5\x01\n" +
	"\rUnwrapRequest\x12:\n" +
	"\x04blob\x18\x01 \x01(\v2&.openbao.attestedunseal.v1.WrappedBlobR\x04blob\x12\x10\n" +
	"\x03aad\x18\x02 \x01(\fR\x03aad\x12G\n" +
	"\bevidence\x18\x03 \x01(\v2+.openbao.attestedunseal.v1.EvidenceEnvelopeR\bevidence\x12=\n" +
	"\x05audit\x18\x04 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"u\n" +
	"\x0eUnwrapResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12E\n" +
	"\bdecision\x18\x02 \x01(\v2).openbao.attestedunseal.v1.PolicyDecisionR\bdecision\"m\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\x05audit\x18\x02 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"\xc5\x01\n" +
	"\x0eStatusResponse\x129\n" +
	"\x04keys\x18\x01 \x03(\v2%.openbao.attestedunseal.v1.KeyVersionR\x04keys\x12\"\n" +
	"\ractive_key_id\x18\x02 \x01(\tR\vactiveKeyId\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12>\n" +
	"\x06errors\x18\x04 \x03(\v2&.openbao.attestedunseal.v1.BrokerErrorR\x06errors\"X\n" +
	"\x17EnrollmentStatusRequest\x12=\n" +
	"\x05audit\x18\x01 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"V\n" +
	"\x18EnrollmentStatusResponse\x12 \n" +
	"\vimplemented\x18\x01 \x01(\bR\vimplemented\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x15RecoveryStatusRequest\x12=\n" +
	"\x05audit\x18\x01 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"T\n" +
	"\x16RecoveryStatusResponse\x12 \n" +
	"\vimplemented\x18\x01 \x01(\bR\vimplemented\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x12AdminStatusRequest\x12=\n" +
	"\x05audit\x18\x01 \x01(\v2'.openbao.attestedunseal.v1.AuditContextR\x05audit\"Q\n" +
	"\x13AdminStatusResponse\x12 \n" +
	"\vimplemented\x18\x01 \x01(\bR\vimplemented\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x93\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eOPERATION_WRAP\x10\x01\x12\x14\n" +
	"\x10OPERATION_UNWRAP\x10\x02\x12\x14\n" +
	"\x10OPERATION_ENROLL\x10\x03\x12\x14\n" +
	"\x10OPERATION_ROTATE\x10\x04\x12\x15\n" +
	"\x11OPERATION_RECOVER\x10\x05*\x8e\x01\n" +
	"\x13AttestationProvider\x12$\n" +
	" ATTESTATION_PROVIDER_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fATTESTATION_PROVIDER_TPM2_QUOTE\x10\x01\x12,\n" +
	"(ATTESTATION_PROVIDER_KUBERNETES_WORKLOAD\x10\x02*}\n" +
	"\x13PolicyDecisionState\x12%\n" +
	"!POLICY_DECISION_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPOLICY_DECISION_STATE_ALLOW\x10\x01\x12\x1e\n" +
	"\x1aPOLICY_DECISION_STATE_DENY\x10\x02*\x8b\x01\n" +
	"\tKeyStatus\x12\x1a\n" +
	"\x16KEY_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KEY_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11KEY_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17KEY_STATUS_DECRYPT_ONLY\x10\x03\x12\x16\n" +
	"\x12KEY_STATUS_RETIRED\x10\x04*\xbe\x01\n" +
	"\x12NodeEvidenceStatus\x12$\n" +
	" NODE_EVIDENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNODE_EVIDENCE_STATUS_FRESH\x10\x01\x12\x1e\n" +
	"\x1aNODE_EVIDENCE_STATUS_STALE\x10\x02\x12 \n" +
	"\x1cNODE_EVIDENCE_STATUS_MISSING\x10\x03\x12 \n" +
	"\x1cNODE_EVIDENCE_STATUS_INVALID\x10\x04*\xa5\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x03\x12\x1c\n" +
	"\x18ERROR_CODE_KEY_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_KEY_NOT_USABLE\x10\x05\x12!\n" +
	"\x1dERROR_CODE_ATTESTATION_FAILED\x10\x06\x12!\n" +
	"\x1dERROR_CODE_BROKER_UNAVAILABLE\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\b2\x8e\x03\n" +
	"\rUnsealService\x12f\n" +
	"\tChallenge\x12+.openbao.attestedunseal.v1.ChallengeRequest\x1a,.openbao.attestedunseal.v1.ChallengeResponse\x12W\n" +
	"\x04Wrap\x12&.openbao.attestedunseal.v1.WrapRequest\x1a'.openbao.attestedunseal.v1.WrapResponse\x12]\n" +
	"\x06Unwrap\x12(.openbao.attestedunseal.v1.UnwrapRequest\x1a).openbao.attestedunseal.v1.UnwrapResponse\x12]\n" +
	"\x06Status\x12(.openbao.attestedunseal.v1.StatusRequest\x1a).openbao.attestedunseal.v1.StatusResponse2\x86\x01\n" +
	"\x11EnrollmentService\x12q\n" +
	"\x06Status\x122.openbao.attestedunseal.v1.EnrollmentStatusRequest\x1a3.openbao.attestedunseal.v1.EnrollmentStatusResponse2\x80\x01\n" +
	"\x0fRecoveryService\x12m\n" +
	"\x06Status\x120.openbao.attestedunseal.v1.RecoveryStatusRequest\x1a1.openbao.attestedunseal.v1.RecoveryStatusResponse2w\n" +
	"\fAdminService\x12g\n" +
	"\x06Status\x12-.openbao.attestedunseal.v1.AdminStatusRequest\x1a..openbao.attestedunseal.v1.AdminStatusResponseBLZJgithub.com/adfinis/openbao-attested-unseal/internal/protocol/v1;protocolv1b\x06proto3"

var (
	file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescOnce sync.Once
	file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescData []byte
)

func file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescGZIP() []byte {
	file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescOnce.Do(func() {
		file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openbao_attestedunseal_v1_attestedunseal_proto_rawDesc), len(file_openbao_attestedunseal_v1_attestedunseal_proto_rawDesc)))
	})
	return file_openbao_attestedunseal_v1_attestedunseal_proto_rawDescData
}

var file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_openbao_attestedunseal_v1_attestedunseal_proto_goTypes = []any{
	(Operation)(0),                   // 0: openbao.attestedunseal.v1.Operation
	(AttestationProvider)(0),         // 1: openbao.attestedunseal.v1.AttestationProvider
	(PolicyDecisionState)(0),         // 2: openbao.attestedunseal.v1.PolicyDecisionState
	(KeyStatus)(0),                   // 3: openbao.attestedunseal.v1.KeyStatus
	(NodeEvidenceStatus)(0),          // 4: openbao.attestedunseal.v1.NodeEvidenceStatus
	(ErrorCode)(0),                   // 5: openbao.attestedunseal.v1.ErrorCode
	(*AuditContext)(nil),             // 6: openbao.attestedunseal.v1.AuditContext
	(*KeyRef)(nil),                   // 7: openbao.attestedunseal.v1.KeyRef
	(*KeyVersion)(nil),               // 8: openbao.attestedunseal.v1.KeyVersion
	(*BrokerError)(nil),              // 9: openbao.attestedunseal.v1.BrokerError
	(*ChallengeRequest)(nil),         // 10: openbao.attestedunseal.v1.ChallengeRequest
	(*ChallengeResponse)(nil),        // 11: openbao.attestedunseal.v1.ChallengeResponse
	(*Claim)(nil),                    // 12: openbao.attestedunseal.v1.Claim
	(*ClaimsEnvelope)(nil),           // 13: openbao.attestedunseal.v1.ClaimsEnvelope
	(*EvidenceEnvelope)(nil),         // 14: openbao.attestedunseal.v1.EvidenceEnvelope
	(*NodeEvidenceRecord)(nil),       // 15: openbao.attestedunseal.v1.NodeEvidenceRecord
	(*NodeEvidenceListRequest)(nil),  // 16: openbao.attestedunseal.v1.NodeEvidenceListRequest
	(*NodeEvidenceListResponse)(nil), // 17: openbao.attestedunseal.v1.NodeEvidenceListResponse
	(*PolicyDecision)(nil),           // 18: openbao.attestedunseal.v1.PolicyDecision
	(*WrappedBlob)(nil),              // 19: openbao.attestedunseal.v1.WrappedBlob
	(*WrapRequest)(nil),              // 20: openbao.attestedunseal.v1.WrapRequest
	(*WrapResponse)(nil),             // 21: openbao.attestedunseal.v1.WrapResponse
	(*UnwrapRequest)(nil),            // 22: openbao.attestedunseal.v1.UnwrapRequest
	(*UnwrapResponse)(nil),           // 23: openbao.attestedunseal.v1.UnwrapResponse
	(*StatusRequest)(nil),            // 24: openbao.attestedunseal.v1.StatusRequest
	(*StatusResponse)(nil),           // 25: openbao.attestedunseal.v1.StatusResponse
	(*EnrollmentStatusRequest)(nil),  // 26: openbao.attestedunseal.v1.EnrollmentStatusRequest
	(*EnrollmentStatusResponse)(nil), // 27: openbao.attestedunseal.v1.EnrollmentStatusResponse
	(*RecoveryStatusRequest)(nil),    // 28: openbao.attestedunseal.v1.RecoveryStatusRequest
	(*RecoveryStatusResponse)(nil),   // 29: openbao.attestedunseal.v1.RecoveryStatusResponse
	(*AdminStatusRequest)(nil),       // 30: openbao.attestedunseal.v1.AdminStatusRequest
	(*AdminStatusResponse)(nil),      // 31: openbao.attestedunseal.v1.AdminStatusResponse
}
var file_openbao_attestedunseal_v1_attestedunseal_proto_depIdxs = []int32{
	7,  // 0: openbao.attestedunseal.v1.KeyVersion.ref:type_name -> openbao.attestedunseal.v1.KeyRef
	3,  // 1: openbao.attestedunseal.v1.KeyVersion.status:type_name -> openbao.attestedunseal.v1.KeyStatus
	5,  // 2: openbao.attestedunseal.v1.BrokerError.code:type_name -> openbao.attestedunseal.v1.ErrorCode
	0,  // 3: openbao.attestedunseal.v1.ChallengeRequest.operation:type_name -> openbao.attestedunseal.v1.Operation
	6,  // 4: openbao.attestedunseal.v1.ChallengeRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	12, // 5: openbao.attestedunseal.v1.ClaimsEnvelope.claims:type_name -> openbao.attestedunseal.v1.Claim
	1,  // 6: openbao.attestedunseal.v1.EvidenceEnvelope.provider:type_name -> openbao.attestedunseal.v1.AttestationProvider
	12, // 7: openbao.attestedunseal.v1.EvidenceEnvelope.normalized_claims:type_name -> openbao.attestedunseal.v1.Claim
	1,  // 8: openbao.attestedunseal.v1.NodeEvidenceRecord.provider:type_name -> openbao.attestedunseal.v1.AttestationProvider
	12, // 9: openbao.attestedunseal.v1.NodeEvidenceRecord.claims:type_name -> openbao.attestedunseal.v1.Claim
	4,  // 10: openbao.attestedunseal.v1.NodeEvidenceRecord.status:type_name -> openbao.attestedunseal.v1.NodeEvidenceStatus
	9,  // 11: openbao.attestedunseal.v1.NodeEvidenceRecord.errors:type_name -> openbao.attestedunseal.v1.BrokerError
	6,  // 12: openbao.attestedunseal.v1.NodeEvidenceListRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	15, // 13: openbao.attestedunseal.v1.NodeEvidenceListResponse.evidence:type_name -> openbao.attestedunseal.v1.NodeEvidenceRecord
	18, // 14: openbao.attestedunseal.v1.NodeEvidenceListResponse.decision:type_name -> openbao.attestedunseal.v1.PolicyDecision
	2,  // 15: openbao.attestedunseal.v1.PolicyDecision.state:type_name -> openbao.attestedunseal.v1.PolicyDecisionState
	9,  // 16: openbao.attestedunseal.v1.PolicyDecision.errors:type_name -> openbao.attestedunseal.v1.BrokerError
	7,  // 17: openbao.attestedunseal.v1.WrappedBlob.key:type_name -> openbao.attestedunseal.v1.KeyRef
	7,  // 18: openbao.attestedunseal.v1.WrapRequest.requested_key:type_name -> openbao.attestedunseal.v1.KeyRef
	14, // 19: openbao.attestedunseal.v1.WrapRequest.evidence:type_name -> openbao.attestedunseal.v1.EvidenceEnvelope
	6,  // 20: openbao.attestedunseal.v1.WrapRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	19, // 21: openbao.attestedunseal.v1.WrapResponse.blob:type_name -> openbao.attestedunseal.v1.WrappedBlob
	18, // 22: openbao.attestedunseal.v1.WrapResponse.decision:type_name -> openbao.attestedunseal.v1.PolicyDecision
	19, // 23: openbao.attestedunseal.v1.UnwrapRequest.blob:type_name -> openbao.attestedunseal.v1.WrappedBlob
	14, // 24: openbao.attestedunseal.v1.UnwrapRequest.evidence:type_name -> openbao.attestedunseal.v1.EvidenceEnvelope
	6,  // 25: openbao.attestedunseal.v1.UnwrapRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	18, // 26: openbao.attestedunseal.v1.UnwrapResponse.decision:type_name -> openbao.attestedunseal.v1.PolicyDecision
	6,  // 27: openbao.attestedunseal.v1.StatusRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	8,  // 28: openbao.attestedunseal.v1.StatusResponse.keys:type_name -> openbao.attestedunseal.v1.KeyVersion
	9,  // 29: openbao.attestedunseal.v1.StatusResponse.errors:type_name -> openbao.attestedunseal.v1.BrokerError
	6,  // 30: openbao.attestedunseal.v1.EnrollmentStatusRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	6,  // 31: openbao.attestedunseal.v1.RecoveryStatusRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	6,  // 32: openbao.attestedunseal.v1.AdminStatusRequest.audit:type_name -> openbao.attestedunseal.v1.AuditContext
	10, // 33: openbao.attestedunseal.v1.UnsealService.Challenge:input_type -> openbao.attestedunseal.v1.ChallengeRequest
	20, // 34: openbao.attestedunseal.v1.UnsealService.Wrap:input_type -> openbao.attestedunseal.v1.WrapRequest
	22, // 35: openbao.attestedunseal.v1.UnsealService.Unwrap:input_type -> openbao.attestedunseal.v1.UnwrapRequest
	24, // 36: openbao.attestedunseal.v1.UnsealService.Status:input_type -> openbao.attestedunseal.v1.StatusRequest
	26, // 37: openbao.attestedunseal.v1.EnrollmentService.Status:input_type -> openbao.attestedunseal.v1.EnrollmentStatusRequest
	28, // 38: openbao.attestedunseal.v1.RecoveryService.Status:input_type -> openbao.attestedunseal.v1.RecoveryStatusRequest
	30, // 39: openbao.attestedunseal.v1.AdminService.Status:input_type -> openbao.attestedunseal.v1.AdminStatusRequest
	11, // 40: openbao.attestedunseal.v1.UnsealService.Challenge:output_type -> openbao.attestedunseal.v1.ChallengeResponse
	21, // 41: openbao.attestedunseal.v1.UnsealService.Wrap:output_type -> openbao.attestedunseal.v1.WrapResponse
	23, // 42: openbao.attestedunseal.v1.UnsealService.Unwrap:output_type -> openbao.attestedunseal.v1.UnwrapResponse
	25, // 43: openbao.attestedunseal.v1.UnsealService.Status:output_type -> openbao.attestedunseal.v1.StatusResponse
	27, // 44: openbao.attestedunseal.v1.EnrollmentService.Status:output_type -> openbao.attestedunseal.v1.EnrollmentStatusResponse
	29, // 45: openbao.attestedunseal.v1.RecoveryService.Status:output_type -> openbao.attestedunseal.v1.RecoveryStatusResponse
	31, // 46: openbao.attestedunseal.v1.AdminService.Status:output_type -> openbao.attestedunseal.v1.AdminStatusResponse
	40, // [40:47] is the sub-list for method output_type
	33, // [33:40] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_openbao_attestedunseal_v1_attestedunseal_proto_init() }
func file_openbao_attestedunseal_v1_attestedunseal_proto_init() {
	if File_openbao_attestedunseal_v1_attestedunseal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openbao_attestedunseal_v1_attestedunseal_proto_rawDesc), len(file_openbao_attestedunseal_v1_attestedunseal_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_openbao_attestedunseal_v1_attestedunseal_proto_goTypes,
		DependencyIndexes: file_openbao_attestedunseal_v1_attestedunseal_proto_depIdxs,
		EnumInfos:         file_openbao_attestedunseal_v1_attestedunseal_proto_enumTypes,
		MessageInfos:      file_openbao_attestedunseal_v1_attestedunseal_proto_msgTypes,
	}.Build()
	File_openbao_attestedunseal_v1_attestedunseal_proto = out.File
	file_openbao_attestedunseal_v1_attestedunseal_proto_goTypes = nil
	file_openbao_attestedunseal_v1_attestedunseal_proto_depIdxs = nil
}
