// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: openbao/attestedunseal/v1/attestedunseal.proto

package protocolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnsealBrokerService_Challenge_FullMethodName = "/openbao.attestedunseal.v1.UnsealBrokerService/Challenge"
	UnsealBrokerService_Wrap_FullMethodName      = "/openbao.attestedunseal.v1.UnsealBrokerService/Wrap"
	UnsealBrokerService_Unwrap_FullMethodName    = "/openbao.attestedunseal.v1.UnsealBrokerService/Unwrap"
	UnsealBrokerService_Status_FullMethodName    = "/openbao.attestedunseal.v1.UnsealBrokerService/Status"
)

// UnsealBrokerServiceClient is the client API for UnsealBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnsealBrokerServiceClient interface {
	Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	Wrap(ctx context.Context, in *WrapRequest, opts ...grpc.CallOption) (*WrapResponse, error)
	Unwrap(ctx context.Context, in *UnwrapRequest, opts ...grpc.CallOption) (*UnwrapResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type unsealBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnsealBrokerServiceClient(cc grpc.ClientConnInterface) UnsealBrokerServiceClient {
	return &unsealBrokerServiceClient{cc}
}

func (c *unsealBrokerServiceClient) Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, UnsealBrokerService_Challenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unsealBrokerServiceClient) Wrap(ctx context.Context, in *WrapRequest, opts ...grpc.CallOption) (*WrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WrapResponse)
	err := c.cc.Invoke(ctx, UnsealBrokerService_Wrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unsealBrokerServiceClient) Unwrap(ctx context.Context, in *UnwrapRequest, opts ...grpc.CallOption) (*UnwrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnwrapResponse)
	err := c.cc.Invoke(ctx, UnsealBrokerService_Unwrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unsealBrokerServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, UnsealBrokerService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnsealBrokerServiceServer is the server API for UnsealBrokerService service.
// All implementations must embed UnimplementedUnsealBrokerServiceServer
// for forward compatibility.
type UnsealBrokerServiceServer interface {
	Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	Wrap(context.Context, *WrapRequest) (*WrapResponse, error)
	Unwrap(context.Context, *UnwrapRequest) (*UnwrapResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedUnsealBrokerServiceServer()
}

// UnimplementedUnsealBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnsealBrokerServiceServer struct{}

func (UnimplementedUnsealBrokerServiceServer) Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Challenge not implemented")
}
func (UnimplementedUnsealBrokerServiceServer) Wrap(context.Context, *WrapRequest) (*WrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wrap not implemented")
}
func (UnimplementedUnsealBrokerServiceServer) Unwrap(context.Context, *UnwrapRequest) (*UnwrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unwrap not implemented")
}
func (UnimplementedUnsealBrokerServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedUnsealBrokerServiceServer) mustEmbedUnimplementedUnsealBrokerServiceServer() {}
func (UnimplementedUnsealBrokerServiceServer) testEmbeddedByValue()                             {}

// UnsafeUnsealBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnsealBrokerServiceServer will
// result in compilation errors.
type UnsafeUnsealBrokerServiceServer interface {
	mustEmbedUnimplementedUnsealBrokerServiceServer()
}

func RegisterUnsealBrokerServiceServer(s grpc.ServiceRegistrar, srv UnsealBrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedUnsealBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnsealBrokerService_ServiceDesc, srv)
}

func _UnsealBrokerService_Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnsealBrokerServiceServer).Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnsealBrokerService_Challenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnsealBrokerServiceServer).Challenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnsealBrokerService_Wrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnsealBrokerServiceServer).Wrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnsealBrokerService_Wrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnsealBrokerServiceServer).Wrap(ctx, req.(*WrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnsealBrokerService_Unwrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnwrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnsealBrokerServiceServer).Unwrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnsealBrokerService_Unwrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnsealBrokerServiceServer).Unwrap(ctx, req.(*UnwrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnsealBrokerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnsealBrokerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnsealBrokerService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnsealBrokerServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnsealBrokerService_ServiceDesc is the grpc.ServiceDesc for UnsealBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnsealBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openbao.attestedunseal.v1.UnsealBrokerService",
	HandlerType: (*UnsealBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Challenge",
			Handler:    _UnsealBrokerService_Challenge_Handler,
		},
		{
			MethodName: "Wrap",
			Handler:    _UnsealBrokerService_Wrap_Handler,
		},
		{
			MethodName: "Unwrap",
			Handler:    _UnsealBrokerService_Unwrap_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _UnsealBrokerService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openbao/attestedunseal/v1/attestedunseal.proto",
}
